spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.199.232/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null #返回的json数据不存在null值
server:
  context-path: /sell

wechat:
  mpAppId: wxa8bb2e54713cb7be
  mpAppSecret: 0ab67e96f71536f279464f6f843e977c
  mchId:
  mchKey:
  keyPath:
  notifyUrl:  http://thyonline.mynatapp.cc/sell/pay/notify
#  mchId: 1483469312
#  mchKey: 06C56A89949D617xxxxxxxxxxx
#  keyPath: /var/weixin_cert/h5.p12
#  notifyUrl: http://thyonline.mynatapp.cc/sell/pay/notify